# kind: Service
# apiVersion: v1
# metadata:
#   name: app1-service
# spec:
#   selector:
#     app: app-1
#   ports:
#     - port: 5678 # Default port for image


apiVersion: v1
kind: Service
metadata:
  name: app-1
  labels:
    app: app-1-dep
spec:
  type: ClusterIP
  ports:
  - port: 8080
    targetPort: 3000
    protocol: TCP
  selector:
    app: app-1
