# TODO: try to find a way to change this file back to using port 8080 instead of 3000
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-configmap
data:
  default.conf: |
    upstream backend {
      server app-1:3000;
      server app-2:3000;
    }
    
    server {
      location / {
        proxy_pass http://backend;
      }
    }
